#!/bin/bash

string=$1

if [ "$#" != "1" ]; then
	echo "Usage: $0 STRING_TO_FIND"
	exit 1
fi

cat /proc/bus/input/devices | grep '^[NH]:' | awk '/^N: .*'$string'.*/ { found = 1; } /^H:/ { if (found == 1) {print $0; exit 0;} } END { exit 1; }' | egrep -o 'event[0-9]+'
